# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Checkout krxbot
    - name: Checkout krxbot
      uses: actions/checkout@v3
      with:
        repository: gunhoon/krxbot
        path: krxbot

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r krxbot/requirements.txt

    - name: Run main.py
      run: |
        python krxbot/src/main.py

    - name: Commit file
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email '<github-actions@github.com>'
        git add stock_price*
        git commit -m '[Bot] Update file'


    - name: GitHub Push
      run: |
        git status
